### ISSUE TITLE
installInertiaVueStack Not implemented yet

### ISSUE THREAD

**Issue by evanh-shumakov** [mercuryseries/inertia-bundle#2]
Trying to execute a "symfony console inertia:install vue --bundler=webpack" and getting an error "In InertiaInstallCommand.php line 223: Not implemented yet!".

![image](https://github.com/user-attachments/assets/d8ed6988-39d2-40bb-b07a-7828a0f938cb)

**Comment by mercuryseries** [comment]
Hi  @evanh-shumakov 
It's because this functionality hasn't been implemented yet.
I need to find some time to address it.
